name: customer-churn-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - mlflow
      - azure-storage-blob
      - azure-identity
      - joblib
      - pyyaml
      - scipy
      - matplotlib
      - tqdm
      - azureml-core
      - azureml-defaults
      - azureml-mlflow