name: customer-churn-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - numpy
      - pandas
      - azureml-mlflow==1.42.0
      - mlflow-skinny==2.3.2
      - scikit-learn
      - joblib
      - azure-cli
      - azure-identity
