name: customer-churn-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ruamel.yaml=0.17.21
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - mlflow
      - joblib
      - pyyaml
      - scipy
      - matplotlib
      - tqdm
      - azure-cli
      - azure-identity
